PX4/Devguide

book/SUMMARY.md, book/ros-mavros.md
I'm going to **Attempt** to document MAVROS as I am walking through it as a user.  This first page merely gives me a starting point and has install instructions copied,pasted, and formatted from the mavros README.md.
=> Added a MAVROS Overview that includes install instructions

book/SUMMARY.md, book/offboard-control-fw.md, book/offboard-control-hw.md, book/offboard-control.md
Started basic info on offboard control
* Basic things that people should know before starting
* Example hardware setups (no wiring yet)
* Firmware setup
I'm not sure how to structure the mavros part, I don't want it to be redundant with the ROS section.
=> Start offboard docs

book/SUMMARY.md, book/external-position.md
@LorenzMeier Done ;)
Highlighting not working for me ATM.
=> Add external position estimation details

book/airframes-vtol-caipiroshka.md
=> Fix typo in link

book/uavcan-node-firmware.md
@LorenzMeier 
These update are for https://github.com/PX4/Firmware/pull/3242
We need to ask @bendyer to update The esc 1.4 repo' tools and the description below.
=> Updates tied to https://github.com/PX4/Firmware/pull/3242 Needs Ben's input

book/hardware-snapdragon.md, book/starting-installing-linux.md
Signed-off-by: Mark Charlebois <charlebm@gmail.com>
=> Updated Snapdragon Flight HW page

book/SUMMARY.md, book/advanced-camera-trigger.md
Hopefully this isn't documenting something *too* obvious.
Is this the appropriate level of detail or should I cut it down?
=> camera trigger doc

book/advanced-fake-gps.md, book/external-position.md
@LorenzMeier 
- correct spelling mistakes found with https://github.com/lucasdemarchi/codespell
=> correct spelling mistakes

book/starting-installing-linux.md
- after adding user to group dialout a logout and login is required !
=> pix permission problem on linux

README.md
@LorenzMeier 
- add note about how to add a new page
=> add note about how to add a new page

book/uavcan-node-firmware.md
Fixes issue described at https://github.com/PX4/px4esc/issues/15#issuecomment-170504089
=> Fixed reference to the PX4ESC codebase for Pixhawk ESC v1.4

book/uavcan-node-firmware.md
https://github.com/PX4/Devguide/pull/55#issuecomment-171243248
=> Fixes Sapog build instructions

book/simulation-ros-interface.md
Woopsies, made the pull request too early.
Sorry about that :sweat:
=> fix copy-paste error

book/starting-building.md
Signed-off-by: Mark Charlebois <charlebm@gmail.com>
=> Added updated instructions for qurt build

book/starting-building.md
Signed-off-by: Mark Charlebois <charlebm@gmail.com>
=> Fixed some makrdown syntax issues

book/concept-flight-modes.md
=> clarify flight modes

book/simulation-ros-interface.md
Adds instructions for installing (the correct version of) gazebo and its plugins.
Also adds instructions for adding a model programmatically to the simulation environment.
Resolves #94
=> Additional Gazebo Ros Instructions

book/advanced-camera-trigger.md
Updating the camera_trigger chapter with distance based triggering mode.
All different modes are described now.
This documents https://github.com/PX4/Firmware/pull/3774
=> Distance based cam trigger mode

book/dronekit-example.md
=> Dronekit example doc

book/SUMMARY.md
=> Updating summary for dronekit

book/SUMMARY.md, book/dronekit-example.md
=> Consistent spelling 

book/starting-building.md
This should fix wrapping and line too long issues.
Should fix #101 and #88.
=> starting-building: use sh console

book/starting-building.md
I should have updated this a while ago!
Please merge ASAP when travis is happy.
=> starting-building: use current master

book/starting-building.md, book/starting-installing-linux.md
=> Snapdragon improvments

book/SUMMARY.md, book/advanced-gimbal-control.md
This is just a rough start really since there is nothing anywhere at the moment. Would need to be extended later.
=> Added rough gimbal app setup page

book/starting-building.md
This goes together with: https://github.com/PX4/Firmware/pull/4060
=> starting-building: track the config files' name

book/advanced-system-console.md
=> added documentation for DSP shell (qshell)

book/starting-building.md
This needs to be updated as soon as https://github.com/PX4/Firmware/pull/4133 is in.
=> starting-building: update Snapdragon build/upload

book/simulation-gazebo.md
and some missing python dependencies
=> clarify gazebo install on osx

book/SUMMARY.md, book/advanced-switching_state_estimators.md
@jgoppert This is for getting people to know how they can switch estimators.
It would now be nice if we can make links to the documentation of the estimators.
I will do it for EKF2, could you set something up for LPE?
=> added page for switching between estimators

book/advanced-snapdragon.md
Yet another try to fix the URLs.
=> Snapdragon: fix broken URLs

book/advanced-snapdragon.md
=> Fix various Snapdragon

book/starting-building.md
=> Snapdragon: instructions for auto-start

book/SUMMARY.md, book/advanced-uorb.md, book/custom-mavlink-message.md, book/tutorial-hello-sky.md
=> Custom uORB & mavlink messages
